version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 1s
      retries: 5

  db-load:
    build: db-load
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  analytics:
    image: python:3.8
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    volumes:
      - ./analytics:/flask
    environment:
      - FLASK_APP=/flask/app.py
      - FLASK_ENV=development
    command: |
      /bin/bash -c "
        pip install -r /flask/requirements.txt 
        flask run --host=0.0.0.0
      "